### ISSUE TITLE
newArgBuilder should handle nil args

### ISSUE THREAD

**Issue by briancain** [hashicorp/go-argmapper#6]
If a caller passes through a nil argument when calling a dynamic function `callDynamicFunc`, argmapper panics on an invalid memory address:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x653da5]

goroutine 65 [running]:
github.com/hashicorp/go-argmapper.newArgBuilder(0xc001016e00, 0x7, 0x7, 0xc000924f40, 0x4, 0x4)
        /home/brian/go/pkg/mod/github.com/hashicorp/go-argmapper@v0.1.1/args.go:44 +0x125
github.com/hashicorp/go-argmapper.(*Func).argBuilder(0xc0005b1310, 0xc000924f40, 0x4, 0x4, 0xc000924ee0, 0xffffffffffffffff, 0x39)
        /home/brian/go/pkg/mod/github.com/hashicorp/go-argmapper@v0.1.1/func.go:222 +0x51
github.com/hashicorp/go-argmapper.(*Func).Call(0xc0005b1310, 0xc000924f40, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/brian/go/pkg/mod/github.com/hashicorp/go-argmapper@v0.1.1/call.go:17 +0x89
github.com/hashicorp/waypoint/internal/core.(*App).callDynamicFunc(0xc0003d14a0, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc000839b90, 0x0, 0x0, 0xc0005e5e00, 0x2d78ac0, 0xc0005b1310, ...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/core/app.go:252 +0x305
github.com/hashicorp/waypoint/internal/core.(*statusReportOperation).Do(0xc0005ebfc0, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc000839b90, 0xc0003d14a0, 0x33a2800, 0xc000922fa0, 0xc000922fa0, 0x0, ...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/core/app_status_report.go:170 +0x1e5
github.com/hashicorp/waypoint/internal/core.(*App).doOperation(0xc0003d14a0, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc000839b90, 0x33d1be8, 0xc0005ebfc0, 0x0, 0x0, 0x0, ...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/core/operation.go:128 +0x10e7
github.com/hashicorp/waypoint/internal/core.(*App).StatusReport(0xc0003d14a0, 0x33b9c00, 0xc000549cc0, 0x0, 0xc00062d2b0, 0x0, 0x0, 0x0, 0x0)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/core/app_status_report.go:52 +0x3f8
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeStatusReportOp(0xc000c5a270, 0x33b9c00, 0xc000549cc0, 0xc00063b428, 0xc000dfe0c0, 0x0, 0xc000dfe0c0, 0xc000ff7560)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/operation_status_report.go:34 +0x411
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeUpOp(0xc000c5a270, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc0008088c0, 0xc000de42a0, 0xc000dfe0c0, 0x0, 0xc0007ea990, 0x0)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/operation_up.go:99 +0xcb4
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeJob(0xc000c5a270, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc0008088c0, 0x33d61a8, 0xc000ca9200, 0xc000de42a0, 0xc0000560c4, 0x2c, ...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/operation.go:161 +0xdb3
github.com/hashicorp/waypoint/internal/runner.(*Runner).prepareAndExecuteJob(0xc000c5a270, 0x33b9c00, 0xc000549cc0, 0x33ed6b8, 0xc0008088c0, 0x33d61a8, 0xc000ca9200, 0xc000ba6bb0, 0x33d6518, 0xc000b38070, ...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/accept.go:407 +0x507
github.com/hashicorp/waypoint/internal/runner.(*Runner).accept(0xc000c5a270, 0x33b9c00, 0xc000549cc0, 0x0, 0x0, 0x0, 0x0)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/accept.go:276 +0xd5f
github.com/hashicorp/waypoint/internal/runner.(*Runner).Accept(...)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/accept.go:75
github.com/hashicorp/waypoint/internal/runner.(*Runner).AcceptMany(0xc000c5a270, 0x33b9c00, 0xc000845bc0)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/runner/accept.go:26 +0x4b
github.com/hashicorp/waypoint/internal/client.New.func1(0xc00097a0a0, 0xc000c5a270)
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/client/project.go:108 +0x72
created by github.com/hashicorp/waypoint/internal/client.New
        /home/brian/go/src/github.com/hashicorp/waypoint/internal/client/project.go:106 +0x37e
```

Instead, it should probably panic on the argument passed in being nil as a failed precondition so it's clear why the call failed. /cc @evanphx for context from last friday since he helped me debug the reason why I got this error 😄

**Comment by briancain** [comment]
Happy to try to pick this one up and try to fix it, I don't think the fix itself is too bad?

**Comment by mitchellh** [comment]
Might want to give 0.2 a try, I think I fixed this: 10419f7826a3f743dfb304613905eed400be14a9

**Comment by briancain** [comment]
Oh nice @mitchellh ok, will give that a shot tomorrow! I don't think I had that on my branch at the time last week. 👍🏻

**Comment by briancain** [comment]
Yes! Fixed 🔥
